login:
  level:
    org:
      springframework:
        cache: TRACE

server:
   port: 6969

net:
  jmb:
    security:
      baseUrl: http://localhost:8090
      matchers:
        permitAll: /clientApp/**

UserController:
  login: redirige vers le service d'authentification OIDC
