login:
  level:
    org:
      springframework:
        cache: TRACE

server:
   port: 8090

net:
  jmb:
    security:
      baseUrl: http://localhost:6969
      matchers:
        permitAll: /clientApp/**

UserController:
  login: redirige vers le service d'authentification OIDC
